pipeline{
    agent any
    triggers {
        cron('H 23 * * 5') //every Friday
    }
    environment {
        SUDO_PASS = credentials('SUDO')
        GH_TOKEN = credentials('GitHub-Kenzlee')
    }
    stages{
        stage('Checkout') {
            steps {
                git (
                    url: 'https://github.com/Kenzlee51/Jenkins.git'
                    branch: 'main'
                    credentialsId: 'GitHub-token'
            )
        }
    }
        stage('Backup') {
            steps {
                sh 'bash db-backups/svacer_dump-db_jenkins.sh'
            }
        }
    post {
        success {
            echo "Бэкап завершён успешно (сборка #${BUILD_NUMBER})"
        }
        failure {
            echo "Бэкап завершился с ошибкой! (сборка #${BUILD_NUMBER})"
        }
    }
}
